package com.alanbaumgartner.bgsim.enums;

import com.google.gson.annotations.SerializedName;

public enum Hero {
    @SerializedName("Edwin VanCleef") EDWINVANCLEEF,
    @SerializedName("Galakrond") GALAKROND,
    @SerializedName("Trade Prince Gallywix") TRADEPRINCEGALLYWIX,
    @SerializedName("Ragnaros the Firelord") RAGNAROSTHEFIRELORD,
    @SerializedName("The Rat King") THERATKING,
    @SerializedName("Queen Wagtoggle") QUEENWAGTOGGLE,
    @SerializedName("George the Fallen") GEORGETHEFALLEN,
    @SerializedName("A. F. Kay") AFKAY,
    @SerializedName("Millificent Manastorm") MILLIFICENTMANASTORM,
    @SerializedName("Patches the Pirate") PATCHESTHEPIRATE,
    @SerializedName("Giantfin") GIANTFIN,
    @SerializedName("Professor Putricide") PROFESSORPUTRICIDE,
    @SerializedName("The Great Akazamzarak") THEGREATAKAZAMZARAK,
    @SerializedName("The Lich King") THELICHKING,
    @SerializedName("Shudderwock") SHUDDERWOCK,
    @SerializedName("Lich Baz'hial") LICHBAZHIAL,
    @SerializedName("Sindragosa") SINDRAGOSA,
    @SerializedName("Infinite Toki") INFINITETOKI,
    @SerializedName("Nefarian") NEFARIAN,
    @SerializedName("Bartendotron") BARTENDOTRON,
    @SerializedName("The Curator") THECURATOR,
    @SerializedName("Patchwerk") PATCHWERK,
    @SerializedName("Yogg-Saron, Hope's End") YOGGSARONHOPESEND,
    @SerializedName("Dancin' Deryl") DANCINDERYL,
    @SerializedName("Lord Jaraxxus") LORDJARAXXUS,
    @SerializedName("King Mukla") KINGMUKLA,
    @SerializedName("Pyramad") PYRAMAD,
    @SerializedName("Sir Finley Mrrgglton") SIRFINLEYMRRGGLTON,
    @SerializedName("Reno Jackson") RENOJACKSON,
    @SerializedName("Elise Starseeker") ELISESTARSEEKER,
    @SerializedName("Dinotamer Brann") DINOTAMERBRANN,
    @SerializedName("Sylvanas Windrunner") SYLVANASWINDRUNNER,
    @SerializedName("Arch-Villain Rafaam") ARCHVILLAINRAFAAM,
    @SerializedName("Tirion Fordring") TIRIONFORDRING,
    @SerializedName("Millhouse Manastorm") MILLHOUSEMANASTORM,
    @SerializedName("Deathwing") DEATHWING,
    @SerializedName("Ysera") YSERA,
    @SerializedName("Alexstrasza") ALEXSTRASZA,
    @SerializedName("Nozdormu") NOZDORMU,
    @SerializedName("Malygos") MALYGOS,
    @SerializedName("Kel'Thuzad") KELTHUZAD,
}
